import { Inter, Roboto } from 'next/font/google'
import Navbar from '../../components/Navbar/Navbar'
import './globals.css'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--roboto-font',
})

export const metadata = {
  title: 'Fake Store Api App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={roboto.variable}
    >
      <body>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
